### ISSUE TITLE
[feature] add `method.trigger` to the resource

### ISSUE THREAD

**Issue by mikemimik** [mikemimik/pipeline-resource#4]
#### Problem:
The resource should allow more than just `create`, `update`, and `delete` of pipelines. The need to trigger specific jobs in other pipelines, possibly on other teams is needed.

#### Proposed Solution:
Add a new method type `trigger` to the parameters of this resource. This would leverage the `team`, `name`/`name_file`, and new `job` parameters to trigger a specific job in another pipeline.

```
- put: pipeline-tool
  params:
    method: trigger
    team: main
    name: deploy-pipeline-name
    job: trigger-deploy-job
```
